### ISSUE TITLE
Feature Request: Include `userdoc` and `devdoc` in `ContractResult`

### ISSUE THREAD

**Issue by yohamta** [shazow/whatsabi#114]
Hi @shazow,

First and foremost, thank you for developing this incredibly useful library. I would like to propose the following enhancement:

---

### Add `userdoc` and `devdoc` to the `ContractResult` Type

- Including these fields would provide access to the contract's user and developer documentation.

**Implementation Details**
1. Modify the `ContractResult` type to include:
    - `userdoc`: User documentation
    - `devdoc`: Developer documentation
2. Update the relevant functions to parse and include these fields from Sourcify's response.

---

We are willing to submit a pull request to implement this feature if that would be acceptable.

**Comment by shazow** [comment]
Hi @yohamta, sounds good to add these fields if they are returned by default anyway.

Do you know if they are also available in Etherscan's results?

Happy to have you contribute this!

**Comment by yohamta** [comment]
Hi @shazow, thanks for the prompt feedback!

> Do you know if they are also available in Etherscan's results?

From what I understand, Etherscan’s results don’t currently include `userdoc` or `devdoc`. So for now, it might make sense to only add these fields when using the Sourcify loader. In the future, it could be possible to use solc-js to gather them from the source code, which could help extend support to Etherscan, but that’s just an idea!

**Comment by shazow** [comment]
Let's add them as optional fields, so we can set them if they exist.

**Comment by yohamta** [comment]
Understood! I'll prepare the PR shortly.
