### ISSUE TITLE
providers: Incompatibility Between `WithCachedCode()` and `ethers.JsonRpcProvider`

### ISSUE THREAD

**Issue by yohamta** [shazow/whatsabi#133]
The provider parameter passed to `providers.WithCachedCode()` appears to be incompatible with `ethers.JsonRpcProvider`.

### Type error
```sh
Provider is not assignable to parameter of type
Type 'Provider' is missing the following properties from type 'Provider': getStorageAt, getAddress
```

### Reproducible example
```ts
import { ethers } from "ethers";

function invokeAutoload(bytecode: string) {
    const provider = new ethers.JsonRpcProvider(config.rpc);
    const cachedCodeProvider = whatsabi.providers.WithCachedCode(
      provider, // Type error
      {
        [address]: bytecode,
      }
    );
    // ...
}
```

### Proposed Fix
```diff
- export function WithCachedCode(provider: Provider, codeCache: Record<string, string>): Provider {
+ export function WithCachedCode(provider: Provider, codeCache: Record<string, string>): AnyProvider {
    return {
        ...provider,
        async getCode(address: string): Promise<string> {
            if (codeCache[address]) {
                return codeCache[address];
            }
            return await provider.getCode(address);
        }
    };
}
```

If this solution seems appropriate, I’d be happy to go ahead and create a pull request.

**Comment by shazow** [comment]
Good call, let's do that. Thank you!

**Comment by shazow** [comment]
Actually, the `provider` argument is the issue I think, not the return value. I think we'll need to accept `AnyProvider` and convert it using `CompatibleProvider` if it's not already converted.

I'll do the change.

**Comment by shazow** [comment]
Pushed the change here, will do a quick merge and release once CI completes, but please let me know if you have any feedback/suggestions for improvements even after it's merged. :) https://github.com/shazow/whatsabi/pull/134
