### ISSUE TITLE
Feature request: Add Blockscout API support

### ISSUE THREAD

**Issue by yohamta** [shazow/whatsabi#149]
I'd like to propose adding support for the Blockscout API to improve our contract data coverage. The plan is to create a `BlockscoutABILoader` that would fetch contract and ABI information from Blockscout's endpoints.

### Blockscout API Documentation:

- [https://docs.blockscout.com/devs/apis/rest](https://www.google.com/url?sa=E&q=https%3A%2F%2Fdocs.blockscout.com%2Fdevs%2Fapis%2Frest)
- [https://eth.blockscout.com/api-docs](https://www.google.com/url?sa=E&q=https%3A%2F%2Feth.blockscout.com%2Fapi-docs)

If this looks good, I'll follow up with a PR.

**Comment by shazow** [comment]
Sounds great, yes please!
