### ISSUE TITLE
refactor: Use Ox

### ISSUE THREAD

**Issue by shazow** [shazow/whatsabi#151]
WhatsABI only has one runtime dependency right now, and it's ethers.js v6. We should look into using this new lower-level library Ox instead: https://oxlib.sh/

There's only a couple of small places in the main library where we use ethers.js helpers:
https://github.com/search?q=repo%3Ashazow%2Fwhatsabi+path%3Asrc%2F*.ts+%22from+%5C%22ethers%5C%22%22&type=code

Then several more helpers for tests, but that can happen later.

**Comment by jxom** [comment]
Some hints:

```diff
- const f = FunctionFragment.from(el).format();
+ const f = AbiFunction.format(AbiFunction.from(el))
```

```diff
- Fragment.from("function " + a.sig).format("json")
+ AbiItem.from("function " + a.sig")
```

```diff
- selector = FunctionFragment.getSelector(a.name, a.inputs);
+ selector = AbiFunction.getSelector(a)
```

**Comment by shazow** [comment]
@jxom is there a way to do "minimal" signature formatting?

ie. the latter version

```diff
- function swapExactETHForTokens(uint256 amountOutMin, address[] path, address to, uint256 deadline) payable returns (uint256[] amounts)
+ swapExactETHForTokens(uint256,address[],address,uint256)
```

**Comment by jxom** [comment]
That would be a signature right? `.getSignature`
