### ISSUE TITLE
Add support for Etherscan v2 API

### ISSUE THREAD

**Issue by k-thornton** [shazow/whatsabi#157]
Etherscan's V2 API greatly simplifies how you work cross-chain.  No more having to keep a bunch of API keys and use a bunch of baseURLs.  One API key, one URL.

https://docs.etherscan.io/etherscan-v2

**Comment by shazow** [comment]
Good call, we should add that soon.

**Comment by k-thornton** [comment]
> Good call, we should add that soon.

sooner than you think :)

**Comment by shazow** [comment]
Fixed via #163
