### ISSUE TITLE
Loader error collection doesn't work as intended

### ISSUE THREAD

**Issue by k-thornton** [shazow/whatsabi#159]
https://github.com/shazow/whatsabi/blob/1a8c899ed147f00e6c9aad2bada24437dd098561/src/loaders.ts#L124

It looks like the intent was to discard any loaders who couldn't locate the ABI in question.  Turns out that err (which is always an instance of LoaderError), doesn't have a .status property.

As such, instead of continuing when status == 404, it always just throws the error from any included loader, even if others succeed.

**Comment by shazow** [comment]
I believe this was fixed in #163
