### ISSUE TITLE
Samczsun rebranding and URLs for lookups

### ISSUE THREAD

**Issue by Jeko83** [shazow/whatsabi#22]
Samczsun has been rebranded to https://openchain.xyz and the urls for the lookups are now:

https://api.openchain.xyz/signature-database/v1/lookup?function=
https://api.openchain.xyz/signature-database/v1/lookup?event=

Updated them manually in the npm module config files and they work like a charm without chaning anything.
They also have a 'junk' filter that's supposed to get rid of junk methods. parameter &filter=true
Just a heads up for a future commit

**Comment by shazow** [comment]
Thanks for the heads up, I'll update it before the next release. :)
