### ISSUE TITLE
Port to other EVM compatible protocols

### ISSUE THREAD

**Issue by carloscip** [shazow/whatsabi#3]
Is it possible to allow user input of the abi, instead of an ethereum smart contract address so that it might be compatible with Avalanche for example?

**Comment by shazow** [comment]
It just takes EVM bytecode, `selectorsFromBytecode(code)` -- so yes, in however way you get EVM-style bytecode, it will work. I haven't tried it but Avalanche should be fine, let me know if there are issues. :)
