### ISSUE TITLE
Two bugs we encountered during our usage

### ISSUE THREAD

**Issue by apollo789** [shazow/whatsabi#52]
1. ethers V6 doesn't have getStorageAt function, need to change it to getStorage;
2. ethers V6 doesn't have the ethers.providers.InfuraProvider class, it has been moved to ethers.InfuraProvider.

**Comment by shazow** [comment]
Hiya, thanks for giving WhatsABI a try! Which version are you using? I believe this was fixed in the latest release, v0.8. :)

Let me know if v0.8 works for you.

**Comment by apollo789** [comment]
> Well, I clicked directly on the zip that Code downloaded, "version": "0.7.0". Should have gone to Releases to download the latest 0.8.0.Thank you, great project!

**Comment by shazow** [comment]
Yay, awesome! Keep the feedback coming. :) And would be happy to learn more about how you're using whatsabi.
