### ISSUE TITLE
Some proxies failed to resolve.

### ISSUE THREAD

**Issue by apollo789** [shazow/whatsabi#53]
After analyzing a lot of data, most of the addresses are doing a good job of detection. The address below belongs to a proxy, but there is no way to resolve it, I don't know if I'm using the wrong method or what?

TransparentUpgradeableProxy?
"""
Error processing proxy resolver EIP1967Proxy: missing revert data (action="call", data=null, reason=null, transaction={ "data": "0x5c60da1b", "to": "0x3E135c3E981fAe3383A5aE0d323860a34CfAB893" }, invocation=null, revert=null, code=CALL_EXCEPTION, version=6.7.1)
"""

Create2BeaconProxy?
"""
Failed to resolve proxy for address: 0x581acd618ba7ef6d3585242423867adc09e8ed60
Failed to resolve proxy for address: 0xa6a3448ea5f5f15ee6c089279712f720c0e16a7f
Failed to resolve proxy for address: 0xb6fc082fdc4dbe19e85d50bde82214919526cb2a
Failed to resolve proxy for address: 0xc088661f2703e5c011612d6a7ff960ee669f8b56
Failed to resolve proxy for address: 0x9b9278c8eb1e49eb3ced22a2d4e144479f07c7df
Failed to resolve proxy for address: 0x9608b7496838e7e00a57cb681b469666a33d8b20
Failed to resolve proxy for address: 0xe5f74b8e5ece57ef1c129523133b5d19ddf8f19d
Failed to resolve proxy for address: 0x5faf6a2d186448dfa667c51cb3d695c7a6e52d8e
Failed to resolve proxy for address: 0x1b80250c32d5b5e278d03e9843475c56bf0a439e
Failed to resolve proxy for address: 0xb9e068ea140511175b6e487b5b48e993bf11838d
Failed to resolve proxy for address: 0xe1aef926b8c94a3fbbeade65afc94dc02803ed40
Failed to resolve proxy for address: 0x8217772e6fe703f18c5c08ea04ab962395f62aa6
Failed to resolve proxy for address: 0x4af84cfb08b484cd32e4378a4b627a5f009b5117
Failed to resolve proxy for address: 0xcca916ff964fdc93cfbe7d34cd888ff28142e645
Failed to resolve proxy for address: 0xdff8bad97aae5995ba0c8d4bdd36f8b5d577e9e4
Failed to resolve proxy for address: 0xbaf6c73a06afd9e02a4af28901698e52fe3cc973
Failed to resolve proxy for address: 0xb8945c69aeb8ad8e16f1e49eaef5c7e48011d178
Failed to resolve proxy for address: 0x0f7c258ef6abd872dd5481785116556a85856ada
Failed to resolve proxy for address: 0x29f033720d84d0f85c1beccf80e51449c06ca2d2
Failed to resolve proxy for address: 0xeb07c09a72f40818704a70f059d1d2c82cc54327
Failed to resolve proxy for address: 0x574cce720237a9d2e679d9093c508e0cceeb2535
Failed to resolve proxy for address: 0xbd2861c0f43f6e8d571fcfa5a7c77d13d5695ebf
Failed to resolve proxy for address: 0x5cd5623aa41a139021645765cebfb4a82a43f029
Failed to resolve proxy for address: 0xd4108bb1185a5c30ea3f4264fd7783473018ce17
Failed to resolve proxy for address: 0x67b9f46bcba2df84ecd41cc6511ca33507c9f4e9
Failed to resolve proxy for address: 0x64c24088de9c5c9197ced6ce9adce16c802fd844
Failed to resolve proxy for address: 0xbf9b32dae8c5267c9295e875f8943b1224d12975
Failed to resolve proxy for address: 0x29b145edfa80b20a3f6f79b57ef4b1ca33ad2777
Failed to resolve proxy for address: 0x471de8beadecd171de505a707bdf0e783a794126
Failed to resolve proxy for address: 0x60a80cbd47e738c88ff414f304fc9b116be37b92
Failed to resolve proxy for address: 0x2e4c82b9f5aa477aba5594ecf5412e4f42c56b7f
Failed to resolve proxy for address: 0x902cf5373317bb3e42660e9f4e85aa21532c0e44
Failed to resolve proxy for address: 0x490d19e4cca09e552c5b1844410e9163182b44d4
Failed to resolve proxy for address: 0xdacf926c6ed25232db5d64288659784147335f5e
Failed to resolve proxy for address: 0xec3c709993f5deda568d6dab09c90bf533021171
Failed to resolve proxy for address: 0x50ace5c459bc3ba3bc1aad7dfb62f88bb94afa06
Failed to resolve proxy for address: 0x5868125220188b260b31e0b4f7a53d3e965a0907
Failed to resolve proxy for address: 0x88ee509e02cfa939430cb8452e63c296be770f96
Failed to resolve proxy for address: 0x8aab6f7f32f9da2c5efb6ab62d76130aeaa5cf69
Failed to resolve proxy for address: 0x35822eaf02cae69e97f5fa36f0188686fa544e21
Failed to resolve proxy for address: 0xa9e1f9c1ec6ecb103c260c3eda0fa28e2785c57a
Failed to resolve proxy for address: 0x5c0a86a32c129538d62c106eb8115a8b02358d57
Failed to resolve proxy for address: 0x5d1c5dee420004767d3e2fb7aa7c75aa92c33117
Failed to resolve proxy for address: 0x829b97a6218d320e97c0a915eb8a07c4dd408cd5
Failed to resolve proxy for address: 0xd1e9a67c7e0558b55341ffdbbef9d34b9db6f235
Failed to resolve proxy for address: 0xf8f815859a6b3447cbeb04301fa35a86c5272f0d
Failed to resolve proxy for address: 0x7f30476e51d7f6286a74b3b314fff51bc7cead92
Failed to resolve proxy for address: 0x1d47322cddbb832b74d8b584aa42ece998498ebe
Failed to resolve proxy for address: 0xa8d412f570401eaad3059d3d4df6336fb37e17e0
Failed to resolve proxy for address: 0x614a03f9db294c7def83423f9719d22410c1abef
Failed to resolve proxy for address: 0x14d1551e734a324ba148158de9981f17f9de73c4
Failed to resolve proxy for address: 0xc58ad9817a324aafa489d30eaf53376b28a9641e
Failed to resolve proxy for address: 0x8c3ab8544b32d0181d53f0004cc51793101e9536
Failed to resolve proxy for address: 0x28cad0a218d15b7b651a06b444f39e7186b52fcb
Failed to resolve proxy for address: 0x3dfc321b714262902468b024d704f6039b650570
Failed to resolve proxy for address: 0xa813f02f95228642a60f6e3cf5ac0273c4160613
Failed to resolve proxy for address: 0x3e7d590b398a8bd7a12fb6071af197bf74248895
Failed to resolve proxy for address: 0x4723df875d4bfdfe4190236b307ec4a65b00002e
Failed to resolve proxy for address: 0x7f44bb621bd9ddceb02540ea2b51c60d6cc4b430
Failed to resolve proxy for address: 0x4c9725cd7db182d5b23e99855e357e3f4742c137
Failed to resolve proxy for address: 0x8eb40c1805ae6a6ce8e8b09ca0e5bbad5a2af7ca
Failed to resolve proxy for address: 0x2c7a424fc64a78cd263ff767d7af875647fcd3b0
Failed to resolve proxy for address: 0x555cccf378b01c550cc7cc7aa138eec70e4c4f33
Failed to resolve proxy for address: 0x9fcb13e8563fb8954b64d50074be596a651a67f5
Failed to resolve proxy for address: 0xb05827f130d2aac67081d9ca84742a6d199a5d9d
Failed to resolve proxy for address: 0x790a60024bc3aea28385b60480f15a0771f26d09
Failed to resolve proxy for address: 0x366834589352937c88aaad8be569e606d58a3f81
Failed to resolve proxy for address: 0xf6fa4cf51258c21cb94918b1100c99968f32f6e0
Failed to resolve proxy for address: 0xa2999e886a9f4d1bae6ecfec614edfce5d8e06c2
Failed to resolve proxy for address: 0xf78b9bae2f7968918deeda37551b7dd83b6dffea
Failed to resolve proxy for address: 0xba63baffcebb44aa560e5f0671d1049ffa05c1c9
Failed to resolve proxy for address: 0x70f79de002b434ee033ea7e9349c310e18f7eb46
Failed to resolve proxy for address: 0xa183014cef1dfc81cb3fd1dd2ce2ea1380fd983d
Failed to resolve proxy for address: 0xe53e3d446a2ac0d19f6481a2462dd43309f341d7
Failed to resolve proxy for address: 0xd4d5f210a1c6acf2a5d2f7f6ab3158711236c417
Failed to resolve proxy for address: 0xd30dd3b2804d4a41b2c796a4b5ac307b2672e2f3
Failed to resolve proxy for address: 0x8363713fe51ad37a113a1aa1ae61b20e42414e5c
Failed to resolve proxy for address: 0xd7df60f0857cfb0003f389ff338df50ba5c17fde
Failed to resolve proxy for address: 0x663134dc10acac6a5f5ad9d3231c51d71de0f0da
Failed to resolve proxy for address: 0xa07c7cebcd136a5c255ad20534d31cd1afba42e6
Failed to resolve proxy for address: 0x7472fbf0130a71d1241890cf5d068be4778c6154
Failed to resolve proxy for address: 0x2b39eceafe795cd4debca0721f2f68409e3b7df2
Failed to resolve proxy for address: 0x48672352e191b2e78bbc319e1d3e751ffc64439d
Failed to resolve proxy for address: 0x04e037787a6e79e6aaea79dbb7a7c4109f49d4bd
Failed to resolve proxy for address: 0x4a7a4c6cf6f0d0e9542df29974e40b4de2178ebc
Failed to resolve proxy for address: 0x804bc39d5670ca176203556dac06fcd7ed37ddb1
Failed to resolve proxy for address: 0xf80ffb0699b8d97e9fd198ccbc367a47b77a9d1c
Failed to resolve proxy for address: 0xcb48144a9fd2c4fa23905762d4e4257d6136adbc
Failed to resolve proxy for address: 0x164a468709bc32f826979fd20322a3ea676a3481
Failed to resolve proxy for address: 0x08765c76c758da951dc73d3a8863b34752dd76fb
Failed to resolve proxy for address: 0xb91bca4c6a607448a093803b3b2a9a4ed3e9f71e
Failed to resolve proxy for address: 0x7e94fb2a0d2db1ff9c85ac818fd28b8bcb799a8b
Failed to resolve proxy for address: 0x4e4a158159e35cce9c94344d503091d8b2a90952
Failed to resolve proxy for address: 0x90b9162018be1b4b09073eca5925b08d19b63541
Failed to resolve proxy for address: 0xe61186dea096349eb5652d45c16079d56d2c2b22
Failed to resolve proxy for address: 0x7229e4e13dd6668c34026f4baa2e44a704bfa5ae
Failed to resolve proxy for address: 0xc60af90a13173353565832f02a2a48222b97ab15
Failed to resolve proxy for address: 0xb31858b8a49dd6099869b034da14a7a9cad1382b
Failed to resolve proxy for address: 0xbf5c04491638bbb3912092e9e9427e376b6554cb
Failed to resolve proxy for address: 0x3451b4c5395b3fe06aa629af73207cfaa28131d1
Failed to resolve proxy for address: 0x4786d62edf0dc42d905107f8b04bbc2779afe90d
Failed to resolve proxy for address: 0x9251e59b053d9407a16f1bd53a3136f4897d7c06
Failed to resolve proxy for address: 0x66d461ba3f1da2b32bf5b8dca3a40b905ab7c639
Failed to resolve proxy for address: 0xcb784233855c97d8532f8eefa094ba876187a150
Failed to resolve proxy for address: 0xabbdbb92cd58fd2f7dba953855b88ed2a2be1465
Failed to resolve proxy for address: 0x929fd5879847f41f05b6cf3746b4343f38b8741b
Failed to resolve proxy for address: 0x96ad7aee7cf43ae2165c485b40c18cae0eba98b4
Failed to resolve proxy for address: 0x1ea1ccfecc55938a71c67150c41e7eba0743e94c
Failed to resolve proxy for address: 0x11df658567e615f69d23289be8a27a9c260ce297
Failed to resolve proxy for address: 0xcbc439fbb8ef91f64631d13187c8d4c96410e8ca
Failed to resolve proxy for address: 0x65879e73aecfc8a1cc7fe44a2ffb3392721e5652
Failed to resolve proxy for address: 0x47be8559ecbaeb84c759c215497d40334f97d754
Failed to resolve proxy for address: 0x3d21b6f588428fcb9091ebd799feabe3eaf4977f
Failed to resolve proxy for address: 0xaeb780ca1b17e9429f84e15a375491cb5372b4ca
Failed to resolve proxy for address: 0x573f76519bb7fd10c95b38f4ffd569d9a3989c39
Failed to resolve proxy for address: 0x4500dcdcb468979f859c56cfcb1040173c69dde8
Failed to resolve proxy for address: 0xa48f2713a0c92b0395ba964e68079d8b07da729d
"""

Vyper_contract?
"""
Failed to resolve proxy for address: 0x2d5d4869381c4fce34789bc1d38acce747e295ae
Failed to resolve proxy for address: 0x84ca3bf4822a342e9c1ad27bd5fbcf5fc5e37128
Failed to resolve proxy for address: 0xff8f8a38c80b9899a928152d58f219fdccd4306c
Failed to resolve proxy for address: 0xd1a075c806e40d79e32ea09553e7080d5d9d4b29
Failed to resolve proxy for address: 0xf59d66c1d593fb10e2f8c2a6fd2c958792434b9c
Failed to resolve proxy for address: 0xd070f6216ef1f2609dfae2ae7e3d7208b1e993d5
Failed to resolve proxy for address: 0x378cb52b00f9d0921cb46dfc099cff73b42419dc
Failed to resolve proxy for address: 0x16825039dfe2a5b01f3e1e6a2bbf9a576c6f95c4
Failed to resolve proxy for address: 0xd8c620991b8e626c099eaab29b1e3eea279763bb
Failed to resolve proxy for address: 0x6fafca7f49b4fd9dc38117469cd31a1e5aec91f5
Failed to resolve proxy for address: 0x4fdd1b06ef986238446be0f3ea163c1b6fe28cc1
Failed to resolve proxy for address: 0x7f7df0e9a040dda05fc609143cc8da7cc6c59587
Failed to resolve proxy for address: 0xa72ad1293b253522fde41f1104aa432d7669b299
Failed to resolve proxy for address: 0x2807387f1212cb2852ab97cdaa3627daca5e4661
Failed to resolve proxy for address: 0xb85e3fe36a6084985e66d704abd4be4ea51e06ce
Failed to resolve proxy for address: 0xafb6c80ff3cfdae5977df0196f3d35cd65e3c7a3
Failed to resolve proxy for address: 0xba3cfea6514cf5acddeff3167df0b7a4337751bc
Failed to resolve proxy for address: 0x5dc81697fc0b3752c1277d260064374e95e8a18b
Failed to resolve proxy for address: 0xfc1cf3dc111981ea4372e91f437581524f3721be
Failed to resolve proxy for address: 0xe02c8114b66e838e028ae743fee915ba530b24e6
Failed to resolve proxy for address: 0xe4174e39beeebb85c7c36cba68f316a5144e7d08
Failed to resolve proxy for address: 0x817fe0d7935170dc91ccbe4aa3450abde302bf10
Failed to resolve proxy for address: 0x528d50dc9a333f01544177a924893fa1f5b9f748
Failed to resolve proxy for address: 0x59518884eebfb03e90a18adbaaab770d4666471e
Failed to resolve proxy for address: 0x7158c1bee7a0fa5bd6affc77b2309991d7adcdd4
Failed to resolve proxy for address: 0x1f8ad2cec4a2595ff3cda9e8a39c0b1be1a02014
Failed to resolve proxy for address: 0x5120feabd5c21883a4696dbcc5d123d6270637e9
Failed to resolve proxy for address: 0x2dfb14e32e2f8156ec15a2c21c3a6c053af52be8
Failed to resolve proxy for address: 0xdf5110ef6bc751cbaf76d35b8a3f312b581b5173
Failed to resolve proxy for address: 0x8472e9914c0813c4b465927f82e213ea34839173
Failed to resolve proxy for address: 0xfd0877d9095789caf24c98f7cce092fa8e120775
Failed to resolve proxy for address: 0xf11b141be4d1985e41c3aea99417e27603f67c4c
Failed to resolve proxy for address: 0x6d765cbe5bc922694afe112c140b8878b9fb0390
Failed to resolve proxy for address: 0x497590d2d57f05cf8b42a36062fa53ebae283498
Failed to resolve proxy for address: 0x4962b6c40b5e9433e029c5c423f6b1ce7ff28b0f
Failed to resolve proxy for address: 0x2147935d9739da4e691b8ae2e1437492a394ebf5
Failed to resolve proxy for address: 0x63739d137eefab1001245a8bd1f3895ef3e186e7
Failed to resolve proxy for address: 0xce0f1ef5aaab82547acc699d3ab93c069bb6e547
Failed to resolve proxy for address: 0xf962b098ecc4352aa2ad1d4164bd2b8367fd94c3
Failed to resolve proxy for address: 0x71955515adf20cbdc699b8bc556fc7fd726b31b0
Failed to resolve proxy for address: 0x4856a7efbbfcae92ab13c5e2e322fc77647bb856
Failed to resolve proxy for address: 0xa2619fdfb99abeb533a1147461f3f1109c5ade75
Failed to resolve proxy for address: 0xb98df7163e61bf053564bde010985f67279bbcec
Failed to resolve proxy for address: 0xd2c65e20c3fde3f18097e7414e65596e0c83b1a9
Failed to resolve proxy for address: 0x477faf103dadc5fe5baa40951cf7512dcbc18126
Failed to resolve proxy for address: 0x2f194da57aa855caa02ea3ab991fa5d38178b9e6
Failed to resolve proxy for address: 0x49b3e44e54b6220af892dba48ae45f1ea6bc4ae9
Failed to resolve proxy for address: 0xaf322a2edf31490250fdeb0d712621484b09abb6
Failed to resolve proxy for address: 0xac1c90b9c76d56ba2e24f3995f7671c745f8f308
Failed to resolve proxy for address: 0xb32747b4045479b77a8b8eb44029ba12580214f8
Failed to resolve proxy for address: 0x1ae8ccd120a05080d9a01c3b4f627f865685d091
Failed to resolve proxy for address: 0x56a5fd5104a4956898753dfb060ff32882ae0eb4
Failed to resolve proxy for address: 0x3466c90017f82dda939b01e8dbd9b0f97aef8dfc
Failed to resolve proxy for address: 0x7356f09c294cb9c6428ac7327b24b0f29419c181
Failed to resolve proxy for address: 0x0e880118c29f095143dda28e64d95333a9e75a47
Failed to resolve proxy for address: 0x0e8a7717a4fd7694682e7005957dd5d7598bf14a
Failed to resolve proxy for address: 0x314f951d144b397a088ea9eac5218bdc7db2ed4a
Failed to resolve proxy for address: 0xfcf8eda095e37a41e002e266daad7efc1579bc0a
Failed to resolve proxy for address: 0xed0244b688cf059f32f45e38a6ac6e479d6755f6
Failed to resolve proxy for address: 0x8e666277c3de28df68a78ede1274603eeea02d34
Failed to resolve proxy for address: 0x5dcd2999ff0685f6165938ec717b26b48998921c
Failed to resolve proxy for address: 0xa5ed287499e3c192c444336342bc4b0e25f51d88
Failed to resolve proxy for address: 0xa5588426040db2c83db16f640f64c7fb265974d4
Failed to resolve proxy for address: 0x83c8df34c6a9d31b97516791f85bac51ed37d49e
Failed to resolve proxy for address: 0xab2ccd6652a170f8fafff115b03ceb30fe855daf
Failed to resolve proxy for address: 0x0bacea14e683e42059c069bc96187520cb282cb9
Failed to resolve proxy for address: 0x8174bff3c861ef667b5f911884f4f7324b2b9c4f
Failed to resolve proxy for address: 0xda82b333a79cb07ddcec69580088f3d8b8f62915
Failed to resolve proxy for address: 0x23d737c8836977739b9a8dc6ddaf64c67bc936f7
Failed to resolve proxy for address: 0x386af2b835d90bc3c5d4e7ae3b1d27ba0f1d0724
Failed to resolve proxy for address: 0x56c218d200247cc7687b4fac31a371e38f6c8b55
Failed to resolve proxy for address: 0x9df9d1d176702bded106149f29005a9be1277ab4
Failed to resolve proxy for address: 0x6a072ff54db0a61476c53d829cd4ad8c91739825
Failed to resolve proxy for address: 0x4264c78898744167a26f886da6ce763965e4bba1
"""

Failed to resolve proxy for address: 0x9e9404849b9a6dd520bd6199aee5ce7f76c09245

**Comment by shazow** [comment]
Oh that's a great list, thank you! I'll try to tackle some of these next week.

**Comment by shazow** [comment]
[Latest release](https://github.com/shazow/whatsabi/releases) (v0.8.1 or v0.8.2 coming in a moment) should have this fixed (included a few tests from the addresses you included too). Thanks! Please report back if you find more. :)
