### ISSUE TITLE
Add an example env

### ISSUE THREAD

**Issue by SonOfMosiah** [shazow/whatsabi#78]
Would be helpful to have an example env file for running the tests during development.

**Comment by shazow** [comment]
Good call, where's the best place to put it? `.env.example`?

Should be something like

```bash
export INFURA_API_KEY="..."
export ETHERSCAN_API_KEY="..."
export PROVIDER="ethers"  # or "viem"
```

**Comment by SonOfMosiah** [comment]
Yep. A `.env.example` would be good. You can add a small change to the Readme under the Development header that says to get started `cp .env.example .env`
